language: ruby

matrix:
  include:
  - rvm: 2.1
    gemfile: mathtype.ruby-2-2.gemspec
  - rvm: 2.2
    gemfile: mathtype.ruby-2-2.gemspec
  - rvm: 2.3
    before_install:
    - gem update --system
    - gem install bundler
  - rvm: 2.4
    before_install:
    - gem update --system
    - gem install bundler
  - rvm: 2.5
    before_install:
    - gem update --system
    - gem install bundler
  - rvm: 2.6
    before_install:
    - gem update --system
    - gem install bundler